apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taxi-prod
data:
  spring.application.name: "rudrabannataxiservices"
  server.port: "8080"
  APP_LOG_LEVEL: "INFO"
  SHOW_SQL: "false"
  FRONTEND_URL: "http://localhost:3000"
  spring.servlet.multipart.max-file-size: "20MB"
  spring.servlet.multipart.max-request-size: "50MB"
  spring.servlet.multipart.enabled: "true"
  file.upload.directory: "/app/uploads"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.show-sql: "false"
  spring.jpa.properties.hibernate.format_sql: "true"
  spring.jpa.open-in-view: "false"
  management.endpoints.web.exposure.include: "health,info,prometheus,metrics"
  management.endpoint.health.show-details: "always"
  management.endpoint.health.probes.enabled: "true"
  management.prometheus.metrics.export.enabled: "true"
