apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: taxi-prod
type: Opaque
stringData:
  DB_USER: taxiuser
  DB_PASSWORD: Taxi@123
  MYSQL_ROOT_PASSWORD: Str0ngP@ssw0rd!
  DB_URL: jdbc:mysql://mysql-service:3306/taxi_services?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
