apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: taxi-prod
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: root1234
  MYSQL_ROOT_PASSWORD: root1234
  DB_URL: jdbc:mysql://mysql-service:3306/taxi_services?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true